import "./globals.css";
import { Providers } from "./providers";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar/NavBar";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light text-foreground bg-background">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
